### ISSUE TITLE
hyphenation does not respect non-breaking space

### ISSUE THREAD

**Issue by ffaf1** [ekmett/hyphenation#20]
Non breakable space is not respected by `hyphenate`. Example:

```
λ> hyphenate english_US "the\x00a0table"
["the\160table"]
```
(expected: `["the ta", "ble"]`).

Other repl experiments to check how `hyphenate` behaves with multiword input:

```
λ> hyphenate english_US "organge dolphin"
["or","gange ","dol","phin"]

λ> hyphenate english_US "the table"
["the table"]

```

**Comment by vshabanov** [comment]
`hyphenate` works on words, not sentences. You need to split your text into words first.

**Comment by Mikolaj** [comment]
@vshabanov: what do you mean? "the\x00a0table" is a word, isn't it?

**Comment by vshabanov** [comment]
No, it's to words "the" and "table". '\x00a0' is a space.

You could read a bit more about the issue here https://github.com/ekmett/hyphenation/issues/16#issuecomment-728936619

**Comment by Mikolaj** [comment]
Haha, it's *non-breaking* space. The whole point of nbsp is that it's not separating words, isn't it so? `Char.isSpace` tells you if somehting it a whitespace, not if something separates words. Using it in the latter role is an abuse and needs special handling for non-separators such as nbsp. Do I make sense?

Thank you for the link.

**Comment by vshabanov** [comment]
It's getting too complicated :)

`nbsp` prevents a line break, but it still acts like a whitespace and is visually indistinguishable (or you have `nbsp` in your dictionary? ;). So we still have two words here.

Of course, the very term "word" is complex and language-dependent. Some words may be separated by space, and some may not. But `hyphenate` doesn't do such analysis. If you want it to work with English text, you need to extract words somehow and pass them to the `hyphenate` function.

**Comment by Mikolaj** [comment]
I see. Would what LeTeX does work, that is `the~table` and after `hyphenate` is done, replace `~` with space everywhere?

**Comment by vshabanov** [comment]
I don't understand what you are trying to do.

`hyphenate` does not contain rules with `~` or any other punctuation characters. Perhaps, it's possible to add "the ta-ble" rule, but it's redundant to the simple "ta-ble" rule.

`hyphenate` only works with words built from the language alphabet and `.` to denote the start and the end of the word. You could check it if you look into `hyph-*.chr.txt.gz` and `hyph-*.pat.txt.gz` files in the [/data](https://github.com/ekmett/hyphenation/tree/master/data) directory.

And if some unknown character is found, the result can be unexpected, as the current hyphenation pattern score is overlaid with the score of the next word. As you see, `lookupPattern` returns the current score at the last line:
https://github.com/ekmett/hyphenation/blob/8de1c6afb1b8ed312cbba7ce7b85c339e5d1871b/src/Text/Hyphenation/Pattern.hs#L49-L57

Perhaps it would be better to raise an error here. Or just return an empty score. But it's still quite bad since if we're not separating words, `hyphenationScore` will calculate word length incorrectly, and `hyphenatorLeftMin` and `hyphenatorRightMin` wouldn't work.
For example:
```
> hyphenate english_GB "the table"
["the t","able"]
```

And another side note. There are hyphenation exceptions too. And `ta-ble` is in the exceptions list for US hyphenation rules. So it hyphenates "ta-ble" but doesn't hyphenate "the table" (unlike GB rules, which hyphenate it but not in the expected place).

So, again, you need to separate words somehow.

**Comment by Mikolaj** [comment]
@vshabanov: thank you for elaborating. I'm busy ATM, so let me just paste a snippet from IRC and perhaps @ffaf1 can elaborate further:

> I think hyphenate should tell me if "a man" can be split or needs to be moved whole to the next line
> if I instead split off "a" and "man" and hyphenate tells me "man" should be moved to the next line, I need to backtrack to know that "a" should be moved, too
> that's basically repeating hyphenate's functionality
> I guess it's not very far from writing hyphenate from scratch
> and I may be missing even more subtle cases where context matters
> (I don't know how hyphenate works nor what exactly the language rules are)
> the context being, that if we don't split, a much larger prefix gets moved to the next line than is apparent
> or even some phonetic context IDK

BTW, this is what LaTeX (or any TeX?) does when you write "a~man" --- which you always do in LaTeX. Given that `hyphenation` uses the same data that TeX uses, I hope there is no fundamental incompatibility and, honestly, I'd try to emulate LaTeX in everything (except the design of it as a language), because it's unbeatable in the art of type-setting.

**Comment by vshabanov** [comment]
`hyphenation` works *inside* words (and `~` works *between* them). It won't tell you whether you should insert `nbsp` between "a" and "man" (it depends on context). That's why you use `~` in LaTeX.

`hyphenation` performs syllabification — it produces possible line-break points inside words. There are other such points, like space (it's application dependent). And then comes the layout mechanism, which takes all these points into account. You could add some custom logic, like moving `a` and `the` to the next line if the next word does not fit. But it's out of the scope of the `hyphenation` package.
